// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwEasSNVVFN2zViUjWxtcuAaLB-2o0zWs',
    appId: '1:473711562923:web:3458610eb904954b44e7ee',
    messagingSenderId: '473711562923',
    projectId: 'skillzupp-tech',
    authDomain: 'skillzupp-tech.firebaseapp.com',
    storageBucket: 'skillzupp-tech.appspot.com',
    measurementId: 'G-GDBBB90421',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU1KqARVSj1YXCIHolESQBLZS0FgTAjWY',
    appId: '1:473711562923:android:3961e39e1485137144e7ee',
    messagingSenderId: '473711562923',
    projectId: 'skillzupp-tech',
    storageBucket: 'skillzupp-tech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZAL3VN8JdMgcVHWRJpGgj-Sg4j6WTgtM',
    appId: '1:473711562923:ios:cfb1cd48e854154144e7ee',
    messagingSenderId: '473711562923',
    projectId: 'skillzupp-tech',
    storageBucket: 'skillzupp-tech.appspot.com',
    iosClientId: '473711562923-2n36l4t06386gbv5chns78rooc847dk9.apps.googleusercontent.com',
    iosBundleId: 'com.ios.sk-tech',
  );
}
